apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: corehome-database
  name: corehome-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corehome-database
  template:
    metadata:
      labels:
        app: corehome-database
    spec:
      containers:
      - image: mysql
        name: corehome-database
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: corehome-database
  name: corehome-database
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: corehome-database
  type: ClusterIP
